#!/system/bin/sh

# Using Ktweaks @tytydraco based source

# Stealing ain't cool. Magisk mirror path...
MAGISKTMP="$(magisk --path)" || MAGISKTMP=/sbin

# Avoid crashed at first boot complete
sync;
sleep 0

if [[ "$(id -u)" -ne 0 ]]; then
	echo " ! No root permissions. Exiting."
	exit 1
fi

while [[ "$(getprop sys.boot_completed)" -ne 1 ]]
do
	if [[ ! -d "$MAGISKTMP" ]]; then
		# Using isolation, isolated process
		sleep 0
	fi
done

(while :
do
	sf=$(service list | grep -c "SurfaceFlinger")
	
	if [ $sf -eq 1 ]; then
		service call SurfaceFlinger 1008 i32 1
		service call SurfaceFlinger 1035 i32 0
		service call SurfaceFlinger 1023 i32 0
		break
	else
		sleep 1
	fi
done
) &

aint()
{
	local NAME=$1
	local CONTAINS=$2
	local NEWVAL=$3
	
	if [[ "$(resetprop $NAME)" = *"$CONTAINS"* ]]; then
		resetprop -v -n "$NAME" "$NEWVAL"
	fi
}

write()
{
	if [[ ! -f "$1" ]]; then
		return 1
		chmod +w "$1" 2> /dev/null
	fi
	
	if ! echo "$2" > "$1" 2> /dev/null; then
		echo " ! Isn't executed, read-only $1 → $2"
		return 1
	fi
}

for personal in /sys/block/*/queue/read_ahead_kb
do
	echo 32 > "$personal"
	for build in /sys/block/*/queue/nr_requests
	do
		echo 32 > "$build"
	done
done

# Enabling after post-fs-data.sh 'exec' and you can see it directly from the modpath file...
for personal in /sys/devices/platform/soc/1d84000.ufshc
do
	echo 1 > "$personal"/clkgate_enable
	echo 1 > "$personal"/clkscale_enable
	echo 1 > "$personal"/hibern8_on_idle_enable
	for build in stop
	do
		"$build" logd
		"$build" logd-auditctl
		"$build" logd-reinit
		"$build" statsd
		"$build" traced
		"$build" traced_perf
		"$build" traced
		"$build" probes
	done
done

for personal in /sys/block/*/queue/iostats
do
	echo 0 > "$personal"
	for build in /sys/block/dm-*/queue/iostats
	do
		echo 0 > "$build"
	done 
done 

for personal in /sys/module/*/parameters/debug_mask
do 
	echo 0 > "$personal"
	for build in /sys/module/*/parameters/debug_level
	do 
		echo 0 > "$build"
	done
done

if [ "$(getprop init.svc.logd)" = running ]; then
	stop logd
	if [ "$(getprop init.svc.statsd)" = running ]; then
		stop statsd
	fi
fi

if [ "$(getprop init.svc.perfd)" = running ]; then
	stop perfd
	if [ "$(getprop init.svc.thermald)" = running ]; then
		stop thermald
	fi
fi

for virtonal in /sys/class/graphics/fb0
do
	echo U:1468x3264-0 > "$virtonal"/modes
	echo 4096 > "$virtonal"/bits_per_pixel
	for paraild in /sys/module/ged/parameters
	do
		echo 1 > "$paraild"/ap_self_frc_detection_rate
		echo 1 > "$paraild"/boost_amp
		echo 1 > "$paraild"/boost_extra
		echo 1 > "$paraild"/boost_gpu_enable
		echo 1 > "$paraild"/cpu_boost_policy
		echo 1 > "$paraild"/enable_cpu_boost
		echo 1 > "$paraild"/enable_game_self_frc_detect
		echo 1 > "$paraild"/enable_gpu_boost
		echo 1 > "$paraild"/ged_boost_enable
		echo 1 > "$paraild"/ged_force_mdp_enable
		echo 1 > "$paraild"/ged_smart_boost
		echo 1 > "$paraild"/gpu_dvfs_enable
		echo 1 > "$paraild"/gx_boost_on
		echo 1 > "$paraild"/gx_dfps
		echo 1 > "$paraild"/gx_force_cpu_boost
		echo 1 > "$paraild"/gx_frc_mode
		echo 1 > "$paraild"/gx_game_mode
		echo 1 > "$paraild"/is_GED_KPI_enabled
	done
done

# FDE.AI, FKM default configuration
write /dev/cpuset/cpu_limit/cpus 0-1
write /dev/cpuset/restricted/cpus 0-3
write /dev/cpuset/system-background/cpus 0-3
write /dev/cpuset/background/cpus 0-1
write /dev/cpuset/camera-daemon/cpus 0-3
write /dev/cpuset/cpus 0-3
write /dev/cpuset/foreground/cpus 0-3
write /dev/cpuset/top-app/cpus 0-3
write /dev/stune/background/schedtune.boost 0
write /dev/stune/background/schedtune.prefer_idle 0
write /dev/stune/background/schedtune.uclamp.max max
write /dev/stune/background/schedtune.uclamp.min 0.00
write /dev/stune/camera-daemon/schedtune.boost 0
write /dev/stune/camera-daemon/schedtune.prefer_idle 0
write /dev/stune/camera-daemon/schedtune.uclamp.max max
write /dev/stune/camera-daemon/schedtune.uclamp.min 0.00
write /dev/stune/foreground/schedtune.boost 0
write /dev/stune/foreground/schedtune.prefer_idle 0
write /dev/stune/foreground/schedtune.uclamp.max max
write /dev/stune/foreground/schedtune.uclamp.min 0.00
write /dev/stune/rt/schedtune.boost 0
write /dev/stune/rt/schedtune.prefer_idle 0
write /dev/stune/rt/schedtune.uclamp.max max
write /dev/stune/rt/schedtune.uclamp.min 0.00
write /dev/stune/schedtune.boost 0
write /dev/stune/schedtune.prefer_idle 0
write /dev/stune/top-app/schedtune.boost 69
write /dev/stune/top-app/schedtune.prefer_idle 1
write /dev/stune/top-app/schedtune.uclamp.max max
write /dev/stune/top-app/schedtune.uclamp.min max
write /proc/sys/kernel/random/write_wakeup_threshold 512
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 0
write /proc/sys/kernel/sched_cstate_aware 1
write /proc/sys/kernel/sched_energy_aware 1
write /proc/sys/kernel/sched_latency_ns 10000000
write /proc/sys/kernel/sched_migration_cost_ns 500000
write /proc/sys/kernel/sched_min_granularity_ns 2250000
write /proc/sys/kernel/sched_nr_migrate 32
write /proc/sys/kernel/sched_rr_timeslice_ms 90
write /proc/sys/kernel/sched_rt_period_us 1000000
write /proc/sys/kernel/sched_rt_runtime_us 950000
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/kernel/sched_sync_hint_enable 1
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_util_clamp_max 1024
write /proc/sys/kernel/sched_util_clamp_min 1024
write /proc/sys/kernel/sched_wakeup_granularity_ns 2000000
write /proc/sys/net/ipv4/tcp_congestion_control bic
write /proc/sys/vm/dirty_background_ratio 12
write /proc/sys/vm/dirty_expire_centisecs 1816
write /proc/sys/vm/dirty_ratio 36
write /proc/sys/vm/dirty_writeback_centisecs 5450
write /proc/sys/vm/extra_free_kbytes 13500
write /proc/sys/vm/laptop_mode 0
write /proc/sys/vm/min_free_kbytes 10240
write /proc/sys/vm/oom_kill_allocating_task 0
write /proc/sys/vm/overcommit_ratio 50
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 94
write /sys/block/dm-0/queue/add_random 0
write /sys/block/dm-0/queue/iostats 0
write /sys/block/dm-0/queue/nomerges 2
write /sys/block/dm-0/queue/nr_requests 128
write /sys/block/dm-0/queue/read_ahead_kb 512
write /sys/block/dm-0/queue/rotational 0
write /sys/block/dm-0/queue/rq_affinity 1
write /sys/block/dm-0/queue/scheduler none
write /sys/block/mmcblk0/queue/add_random 0
write /sys/block/mmcblk0/queue/iosched/fifo_batch 16
write /sys/block/mmcblk0/queue/iosched/front_merges 1
write /sys/block/mmcblk0/queue/iosched/read_expire 501
write /sys/block/mmcblk0/queue/iosched/write_expire 5001
write /sys/block/mmcblk0/queue/iosched/writes_starved 2
write /sys/block/mmcblk0/queue/iostats 0
write /sys/block/mmcblk0/queue/nomerges 2
write /sys/block/mmcblk0/queue/nr_requests 128
write /sys/block/mmcblk0/queue/read_ahead_kb 512
write /sys/block/mmcblk0/queue/rotational 0
write /sys/block/mmcblk0/queue/rq_affinity 1
write /sys/block/mmcblk0/queue/scheduler kyber
write /sys/block/mmcblk1/queue/add_random 0
write /sys/block/mmcblk1/queue/iosched/fifo_batch 16
write /sys/block/mmcblk1/queue/iosched/front_merges 1
write /sys/block/mmcblk1/queue/iosched/read_expire 501
write /sys/block/mmcblk1/queue/iosched/write_expire 5001
write /sys/block/mmcblk1/queue/iosched/writes_starved 2
write /sys/block/mmcblk1/queue/iostats 0
write /sys/block/mmcblk1/queue/nomerges 2
write /sys/block/mmcblk1/queue/nr_requests 128
write /sys/block/mmcblk1/queue/read_ahead_kb 512
write /sys/block/mmcblk1/queue/rotational 0
write /sys/block/mmcblk1/queue/rq_affinity 1
write /sys/block/mmcblk1/queue/scheduler kyber
write /sys/block/zram0/comp_algorithm zstd
write /sys/block/zram0/disksize 4294967296
write /sys/block/zram0/initstate 1
write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 1800000
write /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq 850000
write /sys/devices/system/cpu/cpufreq/performance/down_rate_limit_us 1000
write /sys/devices/system/cpu/cpufreq/performance/up_rate_limit_us 1000
write /sys/module/pstore/parameters/compress deflate
write /sys/module/usbhid/parameters/kbpoll 0

UINT_MAX="4294967295" # phase one
SCHED_PERIOD="$((1 * 1000 * 1000))"
SCHED_TASKS="10"

write /dev/graphics/fb0 1
write /dev/stune/foreground/schedtune.prefer_idle 1
write /dev/stune/top-app/schedtune.boost 10
write /dev/stune/top-app/schedtune.prefer_idle 1
write /proc/sys/debug/exception-trace 0
write /proc/sys/fs/dir-notify-enable 0
write /proc/sys/kernel/compat-log 0
write /proc/sys/kernel/perf_cpu_time_max_percent 5
write /proc/sys/kernel/printk 0 0 0 0
write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
write /proc/sys/kernel/sched_migration_cost_ns 5000000
write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
write /proc/sys/kernel/sched_nr_migrate 32
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
write /proc/sys/net/ipv4/tcp_ecn 1
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/net/ipv4/tcp_syncookies 0
write /proc/sys/vm/block_dump 0
write /proc/sys/vm/dirty_background_ratio 10
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/oom_dump_tasks 0
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 100
write /sys/kernel/debug/debug_enabled N
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_cmd 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_ctxt 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_drv 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_mem 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_pwr 0
write /sys/kernel/debug/sched_features HRTICK
write /sys/kernel/debug/tracing/tracing_on 0
write /sys/kernel/fast_charge/force_fast_charge 1
write /sys/kernel/printk_mode/printk_mode 0
write /sys/kernel/tracing/tracing_on 0
write /sys/module/debug/parameters/enable_event_log 0
write /sys/module/ext4/parameters/mballoc_debug 0
write /sys/module/ip6_tunnel/parameters/log_ecn_error N
write /sys/module/logger/parameters/enabled 0
write /sys/module/logger/parameters/log_enabled 0
write /sys/module/mali/parameters/mali_debug_level 0
write /sys/module/mmc_core/parameters/use_spi_crc 0
write /sys/module/msm_show_resume_irq/parameters/debug_mask 0
write /sys/module/printk/parameters/console_suspend Y
write /sys/module/printk/parameters/cpu N
write /sys/module/printk/parameters/ignore_loglevel Y
write /sys/module/printk/parameters/pid N
write /sys/module/printk/parameters/time N
write /sys/module/rmnet_data/parameters/rmnet_data_log_level 0
write /sys/module/rpm_smd/parameters/debug_mask 0
write /sys/module/subsystem_restart/parameters/enable_ramdumps 0
write dev/cpuset/background/cpus 0-3
write dev/cpuset/foreground/cpus 0-7

if grep -q android /proc/cmdline; then
	ANDROID=true
fi

write /d/tracing/tracing_on 0
write /proc/sys/kernel/hung_task_timeout_secs 0
write /proc/sys/kernel/panic 0
write /proc/sys/kernel/panic_on_oops 0
write /proc/sys/kernel/perf_cpu_time_max_percent 3
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
write /proc/sys/kernel/sched_migration_cost_ns 5000000
write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
write /proc/sys/kernel/softlockup_panic 0
write /proc/sys/vm/panic_on_oom 0
write /sys/kernel/debug/rpm_log 0
write /sys/kernel/printk_mode/printk_mode 0
write /sys/module/rmnet_data/parameters/rmnet_data_log_level 0

if [[ "$ANDROID" == true ]]; then
	write /proc/sys/kernel/sched_min_task_util_for_colocation 0
fi

write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/kernel/sched_nr_migrate 4
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/net/ipv4/tcp_ecn 1
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/net/ipv4/tcp_syncookies 0
write /proc/sys/vm/dirty_background_ratio 3
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 200

if [[ -f "/sys/kernel/debug/sched_features" ]]; then
	write /sys/kernel/debug/sched_features NEXT_BUDDY
	write /sys/kernel/debug/sched_features NO_TTWU_QUEUE
fi

if [[ "$ANDROID" == true ]]; then
	if [[ -d "/dev/stune/" ]]; then
		write /dev/stune/top-app/schedtune.prefer_idle 1
		write /dev/stune/top-app/schedtune.boost 1
	fi
fi

for cpu in /sys/devices/system/cpu/cpu*/cpufreq
do
	avail_govs="$(cat "$cpu/scaling_available_governors")"
	
	for governor in powersave conservative userspace ondemand interactive schedplus schedutil performance
	do
		if [[ "$avail_govs" == *"$governor"* ]]; then
			write "$cpu/scaling_governor" "$governor"
			break
		fi
	done
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" 0
	write "$governor/down_rate_limit_us" 0
	write "$governor/rate_limit_us" 0
	write "$governor/hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" 0
	write "$governor/down_rate_limit_us" 0
	write "$governor/rate_limit_us" 0
	write "$governor/hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" 0
	write "$governor/down_rate_limit_us" 0
	write "$governor/rate_limit_us" 0
	write "$governor/hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/timer_rate" 0
	write "$governor/min_sample_time" 0
	write "$governor/go_hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/timer_rate" 0
	write "$governor/min_sample_time" 0
	write "$governor/go_hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

for queue in /sys/block/*/queue
do
	avail_scheds="$(cat "$queue/scheduler")"
	
	for sched in kyber mq-deadline deadline cfq bfq noop none
	do
		if [[ "$avail_scheds" == *"$sched"* ]]; then
			write "$queue/scheduler" "$sched"
			break
		fi
	done
	
	write "$queue/add_random" 0
	write "$queue/iostats" 0
	write "$queue/read_ahead_kb" 32
	write "$queue/nr_requests" 32
done

UINT_MAX="4294967295" # phase two
SCHED_PERIOD="$((4 * 1000 * 1000))"
SCHED_TASKS="8"

write /dev/cpuset/foreground/boost/cpus 4-7
write /dev/cpuset/foreground/cpus 0-3,4-7
write /dev/cpuset/top-app/cpus 0-7
write /dev/stune/foreground/schedtune.prefer_idle 1
write /dev/stune/top-app/schedtune.boost 10
write /dev/stune/top-app/schedtune.prefer_idle 1
write /proc/sys/debug/exception-trace 0
write /proc/sys/fs/dir-notify-enable 0
write /proc/sys/kernel/compat-log 0
write /proc/sys/kernel/perf_cpu_time_max_percent 3
write /proc/sys/kernel/perf_cpu_time_max_percent 5
write /proc/sys/kernel/printk 0 0 0 0
write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
write /proc/sys/kernel/sched_migration_cost_ns 5000000
write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
write /proc/sys/kernel/sched_nr_migrate 32
write /proc/sys/kernel/sched_nr_migrate 4
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
write /proc/sys/net/ipv4/tcp_ecn 1
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/net/ipv4/tcp_syncookies 0
write /proc/sys/vm/block_dump 0
write /proc/sys/vm/dirty_background_ratio 10
write /proc/sys/vm/dirty_background_ratio 3
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/oom_dump_tasks 0
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 100
write /proc/sys/vm/vfs_cache_pressure 200
write /sys/block/mmcblk0/queue/scheduler mq-deadline
write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay 0
write /sys/devices/system/cpu/cpufreq/performance/align_windows 1
write /sys/devices/system/cpu/cpufreq/performance/boost 1
write /sys/devices/system/cpu/cpufreq/performance/go_hispeed_load 75
write /sys/devices/system/cpu/cpufreq/performance/max_freq_hysteresis 1
write /sys/devices/system/cpu/cpufreq/policy0/scaling_governor performance
write /sys/devices/system/cpu/cpufreq/policy4/scaling_governor performance
write /sys/kernel/debug/debug_enabled N
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_cmd 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_ctxt 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_drv 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_mem 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_pwr 0
write /sys/kernel/debug/sched_features HRTICK
write /sys/kernel/debug/tracing/tracing_on 0
write /sys/kernel/gpu/gpu_governor performance
write /sys/kernel/printk_mode/printk_mode 0
write /sys/kernel/tracing/tracing_on 0
write /sys/module/adreno_idler/parameters/adreno_idler_active 0
write /sys/module/debug/parameters/enable_event_log 0
write /sys/module/ext4/parameters/mballoc_debug 0
write /sys/module/ip6_tunnel/parameters/log_ecn_error N
write /sys/module/lazyplug/parameters/nr_possible_cores 8
write /sys/module/logger/parameters/enabled 0
write /sys/module/logger/parameters/log_enabled 0
write /sys/module/mali/parameters/mali_debug_level 0
write /sys/module/mmc_core/parameters/use_spi_crc 0
write /sys/module/msm_performance/parameters/touchboost 1
write /sys/module/msm_show_resume_irq/parameters/debug_mask 0
write /sys/module/printk/parameters/console_suspend Y
write /sys/module/printk/parameters/cpu N
write /sys/module/printk/parameters/ignore_loglevel Y
write /sys/module/printk/parameters/pid N
write /sys/module/printk/parameters/time N
write /sys/module/rmnet_data/parameters/rmnet_data_log_level 0
write /sys/module/rpm_smd/parameters/debug_mask 0
write /sys/module/subsystem_restart/parameters/enable_ramdumps 0
write dev/cpuset/background/cpus 0-3
write dev/cpuset/foreground/cpus 0-7

if [[ -f "/sys/kernel/debug/sched_features" ]]; then
	write /sys/kernel/debug/sched_features NEXT_BUDDY
	write /sys/kernel/debug/sched_features TTWU_QUEUE
fi

if [[ "$ANDROID" == true ]]; then
	if [[ -d "/dev/stune/" ]]; then
		write /dev/stune/top-app/schedtune.prefer_idle 0
		write /dev/stune/top-app/schedtune.boost 1
	fi
fi

for cpu in /sys/devices/system/cpu/cpu*/cpufreq
do
	avail_govs="$(cat "$cpu/scaling_available_governors")"

	for governor in powersave conservative userspace ondemand interactive schedplus schedutil performance
	do
		if [[ "$avail_govs" == *"$governor"* ]]; then
			write "$cpu/scaling_governor" "$governor"
			break
		fi
	done
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/down_rate_limit_us" "$((4 * SCHED_PERIOD / 1000))"
	write "$governor/rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/down_rate_limit_us" "$((4 * SCHED_PERIOD / 1000))"
	write "$governor/rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/down_rate_limit_us" "$((4 * SCHED_PERIOD / 1000))"
	write "$governor/rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/timer_rate" "$((SCHED_PERIOD / 1000))"
	write "$governor/min_sample_time" "$((SCHED_PERIOD / 1000))"
	write "$governor/go_hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -type d -name powersave -o -name conservative -o -name userspace -o -name ondemand -o -name interactive -o -name schedplus -o -name schedutil -o -name performance | while IFS= read -r governor
do
	write "$governor/timer_rate" "$((SCHED_PERIOD / 1000))"
	write "$governor/min_sample_time" "$((SCHED_PERIOD / 1000))"
	write "$governor/go_hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

for queue in /sys/block/*/queue
do
	avail_scheds="$(cat "$queue/scheduler")"
	
	for sched in kyber mq-deadline deadline cfq bfq noop none
	do
		if [[ "$avail_scheds" == *"$sched"* ]]; then
			write "$queue/scheduler" "$sched"
			break
		fi
	done
	
	write "$queue/add_random" 0
	write "$queue/iostats" 0
	write "$queue/read_ahead_kb" 32
	write "$queue/nr_requests" 32
done

if true; then
	for bjir in powersave conservative userspace ondemand interactive schedplus schedutil performance
	do
		write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor "$bjir"
		write /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor "$bjir"
		write /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor "$bjir"
		write /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor "$bjir"
		for njir in powersave conservative userspace ondemand interactive schedplus schedutil performance
		do
			write /sys/devices/system/cpu/cpufreq/policy1/scaling_governor "$njir"
			write /sys/devices/system/cpu/cpufreq/policy2/scaling_governor "$njir"
			write /sys/devices/system/cpu/cpufreq/policy3/scaling_governor "$njir"
			write /sys/devices/system/cpu/cpufreq/policy4/scaling_governor "$njir"
		done
	done
fi

for amognal in /sys/bus/cpu/devices/*/cpufreq
do
	echo "$UINT_MAX" > "$amognal"/cpuinfo_cur_freq
	echo "$UINT_MAX" > "$amognal"/cpuinfo_max_freq
	echo "$UINT_MAX" > "$amognal"/cpuinfo_min_freq
	echo "$UINT_MAX" > "$amognal"/scaling_cur_freq
	echo "$UINT_MAX" > "$amognal"/scaling_max_freq
	echo "$UINT_MAX" > "$amognal"/scaling_min_freq
done

function config()
{
	swapoff /dev/block/zram0 >/dev/null 2>&1
	echo 1 > /sys/block/zram0/reset
	
	echo 0 > /proc/sys/vm/laptop_mode
	echo 0 > /proc/sys/vm/oom_kill_allocating_task
	echo 0 > /proc/sys/vm/page-cluster
	echo 10 > /proc/sys/vm/dirty_background_ratio
	echo 100 > /proc/sys/vm/swappiness
	echo 100 > /proc/sys/vm/vfs_cache_pressure
	echo 13500 > /proc/sys/vm/extra_free_kbytes
	echo 30 > /proc/sys/vm/dirty_ratio
	echo 3000 > /proc/sys/vm/dirty_expire_centisecs
	echo 3000 > /proc/sys/vm/dirty_writeback_centisecs
	echo 3022 > /proc/sys/vm/min_free_kbytes
	echo 50 > /proc/sys/vm/overcommit_ratio
	
	echo $((4096*8192*16384)) > /sys/block/zram0/disksize
	mkswap /dev/block/zram0 >/dev/null 2>&1
	
	for compild in lzo lz4 zstd
	do
		echo "$compild" > /sys/block/zram0/comp_algorithm
	done
	
	echo 4294967296 > /sys/block/zram0/disksize
	echo 1 > /sys/block/zram0/initstate
	echo 4 > /sys/block/zram0/max_comp_streams
	
	swapon /dev/block/zram0 >/dev/null 2>&1
}

config;

# Using Xvision™(KCAL) @pedro based source

for kcal in /sys/devices/platform/kcal_ctrl.0
do
	echo 1 > "$kcal"/kcal_enable
	echo 275 > "$kcal"/kcal_sat
	echo 253 > "$kcal"/kcal_val
	echo 258 > "$kcal"/kcal_cont
	echo 236 238 240 > "$kcal"/kcal
done

function biglittlecore()
{
	echo 0 >  /sys/devices/system/cpu/cpu0/sched_mostly_idle_freq
	echo 0 >  /sys/devices/system/cpu/cpu1/sched_mostly_idle_freq
	echo 0 >  /sys/devices/system/cpu/cpu2/sched_mostly_idle_freq
	echo 0 >  /sys/devices/system/cpu/cpu4/sched_mostly_idle_freq
	echo 0 >  /sys/devices/system/cpu/cpu6/sched_mostly_idle_freq
	echo 0 > /dev/stune/background/schedtune.boost
	echo 0 > /dev/stune/background/schedtune.colocate
	echo 0 > /dev/stune/background/schedtune.prefer_idle
	echo 0 > /dev/stune/background/schedtune.sched_boost_no_override
	echo 0 > /dev/stune/foreground/schedtune.boost
	echo 0 > /dev/stune/foreground/schedtune.colocate
	echo 0 > /dev/stune/foreground/schedtune.prefer_idle
	echo 0 > /dev/stune/foreground/schedtune.sched_boost_no_override
	echo 0 > /dev/stune/schedtune.boost
	echo 0 > /dev/stune/schedtune.colocate
	echo 0 > /dev/stune/schedtune.prefer_idle
	echo 0 > /dev/stune/schedtune.sched_boost_no_override
	echo 0 > /dev/stune/top-app/schedtune.boost
	echo 0 > /dev/stune/top-app/schedtune.prefer_idle
	echo 0 > /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay
	echo 0-7 > /dev/cpuset/audio-app/cpus
	echo 0-7 > /dev/cpuset/background/cpus
	echo 0-7 > /dev/cpuset/camera-daemon/cpus
	echo 0-7 > /dev/cpuset/foreground/boost/cpus
	echo 0-7 > /dev/cpuset/foreground/cpus
	echo 0-7 > /dev/cpuset/rt/cpus
	echo 0-7 > /dev/cpuset/top-app/cpus
	echo 1 > /dev/stune/background/schedtune.sched_boost_enabled
	echo 1 > /dev/stune/foreground/schedtune.sched_boost_enabled
	echo 1 > /dev/stune/schedtune.sched_boost_enabled
	echo 1 > /dev/stune/top-app/schedtune.colocate
	echo 1 > /dev/stune/top-app/schedtune.sched_boost_enabled
	echo 1 > /dev/stune/top-app/schedtune.sched_boost_no_override
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/align_windows
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/boost
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/max_freq_hysteresis
	echo 1 > /sys/module/msm_performance/parameters/touchboost
	echo 8 > /sys/module/lazyplug/parameters/nr_possible_cores
	echo 90 > /sys/devices/system/cpu/cpufreq/performance/go_hispeed_load
	echo performance > /sys/class/kgsl/kgsl-3d0/devfreq/governor
	echo performance > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo performance > /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
	echo performance > /sys/devices/system/cpu/cpufreq/policy6/scaling_governor
	echo 0 > /sys/devices/system/cpu/isolated
	echo 0 > /sys/devices/system/cpu/offline
	echo 0 > /sys/devices/system/cpu/uevent
	echo 1 > /sys/devices/system/cpu/cpufreq/policy0/schedutil/iowait_boost_enable
	echo 1 > /sys/devices/system/cpu/cpufreq/policy4/schedutil/iowait_boost_enable
	echo Y > /sys/module/workqueue/parameters/power_efficient
	echo 0 > /sys/module/ged/parameters/ged_force_mdp_enable
	echo 1 > /sys/module/ged/parameters/boost_amp
	echo 1 > /sys/module/ged/parameters/boost_extra
	echo 1 > /sys/module/ged/parameters/boost_gpu_enable
	echo 1 > /sys/module/ged/parameters/enable_cpu_boost
	echo 1 > /sys/module/ged/parameters/enable_game_self_frc_detect
	echo 1 > /sys/module/ged/parameters/enable_gpu_boost
	echo 1 > /sys/module/ged/parameters/ged_boost_enable
	echo 1 > /sys/module/ged/parameters/gx_3D_benchmark_on
	echo 1 > /sys/module/ged/parameters/gx_frc_mode
	echo 1 >/sys/module/ged/parameters/gx_force_cpu_boost
	echo 1 >/sys/module/ged/parameters/gx_game_mode
	echo 10 > /sys/module/ged/parameters/gpu_idle
	echo 100 > /sys/module/ged/parameters/cpu_boost_policy
	echo 100 > /sys/module/ged/parameters/ged_smart_boost
	
	echo 1 768000:90 > /sys/devices/system/cpu/cpu4/cpufreq/performance/target_loads
	echo 1 960000:85 1094400:90 1344000:80 > /sys/devices/system/cpu/cpu0/cpufreq/performance/target_loads
	echo 1 960000:85 1094400:90 > /sys/devices/system/cpu/cpufreq/performance/target_loads
	echo 19000 1094400:39000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/above_hispeed_delay
	echo 19000 1094400:39000 > /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay
	echo 19000 1401600:39000 > /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay
	echo 85 1401600:80 > /sys/devices/system/cpu/cpufreq/performance/target_loads
	
	echo 0 > /sys/android_touch/doubletap2wake
	echo 0 > /sys/android_touch/sweep2sleep
	echo 0 > /sys/android_touch/sweep2wake
	
	if true; then
		for perfonal in powersave conservative userspace ondemand interactive schedplus schedutil performance
		do
			echo "$perfonal" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor
			echo "$perfonal" > /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor
		done
	fi
	
	echo 0 0 > /proc/ppm/policy_status
	echo 0 > /proc/ppm/enabled
	echo 1 0 > /proc/ppm/policy_status
	echo 2 0 > /proc/ppm/policy_status
	echo 3 0 > /proc/ppm/policy_status
	echo 4 0 > /proc/ppm/policy_status
	echo 5 0 > /proc/ppm/policy_status
	echo 6 0 > /proc/ppm/policy_status
	echo 7 0 > /proc/ppm/policy_status
	echo 8 0 > /proc/ppm/policy_status
	echo 9 0 > /proc/ppm/policy_status
	
	echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/performance/rate_limit_us
	echo 0 > /sys/devices/system/cpu/cpu0/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu0/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu1/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu1/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu2/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu2/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu3/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu3/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/performance/rate_limit_us
	echo 0 > /sys/devices/system/cpu/cpu4/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu4/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu5/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu5/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu6/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu6/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu7/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu7/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpufreq/performance/rate_limit_us
	echo 1 > /proc/sys/kernel/sched_prefer_sync_wakee_to_waker
	echo 1 > /proc/sys/kernel/sched_restrict_cluster_spill
	echo 1 > /proc/sys/kernel/sched_restrict_tasks_spread
	echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/performance/use_sched_load
	echo 1 > /sys/devices/system/cpu/cpu0/online
	echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/performance/use_sched_load
	echo 1 > /sys/devices/system/cpu/cpu4/online
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/use_sched_load
	
	echo "$UINT_MAX" > /sys/devices/system/cpu/cpu0/cpufreq/performance/hispeed_freq
	echo "$UINT_MAX" > /sys/devices/system/cpu/cpufreq/performance/hispeed_freq
	echo "$UINT_MAX" > /sys/devices/system/cpu/cpufreq/performance/hispeed_freq
	
	echo 19 > /proc/sys/kernel/sched_upmigrate_min_nice
	echo 20 > /proc/sys/kernel/sched_small_task
	echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/timer_rate
	echo 20000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/timer_rate
	echo 20000 > /sys/devices/system/cpu/cpufreq/performance/timer_rate
	echo 200000 > /proc/sys/kernel/sched_freq_dec_notify
	echo 200000 > /proc/sys/kernel/sched_freq_inc_notify
	echo 3 > /proc/sys/kernel/sched_ravg_hist_size
	echo 3 > /proc/sys/kernel/sched_spill_nr_run
	echo 3 > /proc/sys/kernel/sched_window_stats_policy
	echo 3 > /sys/devices/system/cpu/cpu0/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu1/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu2/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu3/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu4/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu5/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu6/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu7/sched_mostly_idle_nr_run
	echo 30 > /sys/devices/system/cpu/cpu0/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu1/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu2/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu3/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu4/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu5/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu6/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu7/sched_mostly_idle_load
	echo 39000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/above_hispeed_delay
	echo 39000 > /sys/devices/system/cpu/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/sampling_down_factor
	echo 40000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/sampling_down_factor
	echo 40000 > /sys/devices/system/cpu/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpufreq/performance/sampling_down_factor
	echo 50000 > /proc/sys/kernel/sched_freq_dec_notify
	echo 50000 > /proc/sys/kernel/sched_freq_inc_notify
	echo 768000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/hispeed_freq
	echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/performance/go_hispeed_load
	echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/performance/hispeed_load
	echo 85 > /sys/devices/system/cpu/cpu4/cpufreq/performance/hispeed_load
	echo 85 > /sys/devices/system/cpu/cpufreq/performance/go_hispeed_load
	echo 85 > /sys/devices/system/cpu/cpufreq/performance/hispeed_load
	echo 90 > /sys/devices/system/cpu/cpu4/cpufreq/performance/go_hispeed_load
	
	sleep 1
	if true; then
		su 2000 -c "cmd notification post -S bigtext -t 'options by nothing' 'Tag' '
function biglittlecore()
{
	executed, done
}'"; else
		su -lp 2000 -c "cmd notification post -S bigtext -t 'options by nothing' 'Tag' '
function biglittlecore()
{
	executed, done
}'"
	fi
}

biglittlecore;

# Personalidentify you should read this 'https://github.com/LinggaCR17/personalbuild/blob/main/system.prop' before editing any script stuff.
{
	aint dalvik.vm.dexopt-flags v=a,o=v,m=y,u=y
	aint dalvik.vm.heapsize 512m
	aint dalvik.vm.zygotemaxfailedboots 5
	aint debug.atrace.tags.enableflags 0
	aint debug.composition.type dyn
	aint debug.cpurend.vsync false
	aint debug.drm.mode.force 1468x3264@120
	aint debug.egl.buffcount 4
	aint debug.egl.force_msaa 1
	aint debug.egl.hw 1
	aint debug.egl.profiler 1
	aint debug.egl.swapinterval 0
	aint debug.enable.sglscale 1
	aint debug.enabletr false
	aint debug.gr.swapinterval 0
	aint debug.gralloc.enable_fb_ubwc 1
	aint debug.gralloc.gfx_ubwc_disable 0
	aint debug.hwui.capture_skp_enabled false
	aint debug.hwui.disable_draw_defer true
	aint debug.hwui.disable_draw_reorder true
	aint debug.hwui.filter_test_overhead false
	aint debug.hwui.fps_divisor 1
	aint debug.hwui.level 0
	aint debug.hwui.overdraw false
	aint debug.hwui.profile.maxframes 120
	aint debug.hwui.profile false
	aint debug.hwui.render_dirty_regions false
	aint debug.hwui.renderer skiagl
	aint debug.hwui.show_dirty_regions false
	aint debug.hwui.show_layers_updates false
	aint debug.hwui.show_non_rect_clip hide
	aint debug.hwui.skia_atrace_enabled false
	aint debug.hwui.skip_empty_damage true
	aint debug.hwui.skp_filename /sdcard/
	aint debug.hwui.use_buffer_age false
	aint debug.hwui.use_gpu_pixel_buffers false
	aint debug.hwui.use_partial_updates false
	aint debug.kill_allocating_task 0
	aint debug.mdpcomp.4k2kSplit 1
	aint debug.mdpcomp.idletime 600
	aint debug.mdpcomp.idletime 9000
	aint debug.mdpcomp.logs 0
	aint debug.overlayui.enable 1
	aint debug.performance.tuning 1
	aint debug.renderengine.backend skiaglthreaded
	aint debug.sf.disable_backpressure 1
	aint debug.sf.enable_advanced_sf_phase_offset 1
	aint debug.sf.enable_gl_backpressure 1
	aint debug.sf.enable_hwc_vds 1
	aint debug.sf.high_fps.early.app.duration 10000000
	aint debug.sf.high_fps.early.sf.duration 13800000
	aint debug.sf.high_fps.earlyGl.app.duration 10000000
	aint debug.sf.high_fps.earlyGl.sf.duration 13800000
	aint debug.sf.high_fps.hwc.min.duration 8500000
	aint debug.sf.high_fps.late.app.duration 10000000
	aint debug.sf.high_fps.late.sf.duration 13800000
	aint debug.sf.hw 1
	aint debug.sf.latch_unsignaled 1
	aint debug.sf.no_hw_vsync 1
	aint fku.perf.profile 1
	aint force_hw_ui true
	aint hw2d.force 1
	aint hw3d.force 1
	aint hwui.disable_vsync true
	aint hwui.private_hal_readback 1
	aint hwui.render_dirty_regions false
	aint log.tag.stats_log 0
	aint logcat.live disable
	aint logd.logpersistd.enable false
	aint logd.statistics 0
	aint persist.android.strictmode 0
	aint persist.demo.hdmirotationlock false
	aint persist.dev.pm.dyn_samplingrate 1
	aint persist.hwc.mdpcomp.enable true
	aint persist.hwc.ptor.enable true
	aint persist.service.lgospd.enable 0
	aint persist.service.pcsync.enable 0
	aint persist.sys.composition.type dyn
	aint persist.sys.dalvik.hyperthreading true
	aint persist.sys.dalvik.multithread true
	aint persist.sys.force_highendgfx true
	aint persist.sys.purgeable_assets 1
	aint persist.sys.scrollingcache 3
	aint persist.sys.strictmode.disable 1
	aint persist.sys.strictmode.visual 0
	aint persist.sys.ui.hw 1
	aint persist.sys.use_dithering 1
	aint persist.traced.enable 0
	aint persist.vendor.accelerate.charge true
	aint persist.vendor.color.matrix 2
	aint persist.vendor.disable_idle_fps.threshold 1390
	aint persist.vendor.disable_idle_fps true
	aint persist.vendor.product.perf 1
	aint persist.vendor.qti.inputopts.enable true
	aint persist.vendor.qti.inputopts.movetouchslop 0.1
	aint persist.vendor.verbose_logging_enabled false
	aint profiler.force_disable_err_rpt 1
	aint profiler.force_disable_ulog 1
	aint ro.config.disable.hw_accel false
	aint ro.config.enable.hw_accel true
	aint ro.config.low_ram true
	aint ro.fb.mode 1
	aint ro.hardware.vulkan true
	aint ro.hwui.drop_shadow_cache_size 6
	aint ro.hwui.gradient_cache_size 1
	aint ro.hwui.layer_cache_size 48
	aint ro.hwui.path_cache_size 32
	aint ro.hwui.r_buffer_cache_size 8
	aint ro.hwui.text_large_cache_height 1024
	aint ro.hwui.text_large_cache_width 2048
	aint ro.hwui.text_small_cache_height 1024
	aint ro.hwui.text_small_cache_width 1024
	aint ro.hwui.texture_cache_flushrate 0.4
	aint ro.hwui.texture_cache_size 72
	aint ro.hwui.use_vulkan true
	aint ro.kernel.android.checkjni 0
	aint ro.kernel.checkjni 0
	aint ro.logd.kernel false
	aint ro.logd.size.stats 0
	aint ro.logd.size 0
	aint ro.max.fling_velocity 20000
	aint ro.max_pointer_dur 8
	aint ro.min.fling_velocity 18000
	aint ro.min_pointer_dur 8
	aint ro.opengles.version 196610
	aint ro.product.gpu.driver 1
	aint ro.product.max_num_touch 10
	aint ro.product.min_num_touch 10
	aint ro.product.multi_touch_enabled true
	aint ro.sf.compbypass.enable 0
	aint ro.surface_flinger.protected_contents true
	aint ro.vendor.display.default_fps 120
	aint ro.vendor.display.idle_default_fps 120
	aint ro.vendor.display.touch.idle.enable true
	aint ro.vendor.fps.switch.default true
	aint ro.vendor.fps.switch.thermal true
	aint ro.vendor.qti.config.zram true
	aint ro.vendor.qti.core.ctl_max_cpu 8
	aint ro.vendor.qti.core.ctl_min_cpu 4
	aint ro.vendor.qti.sys.fw.bservice_enable true
	aint ro.vendor.tran_perf_plus 1
	aint ro.vold.umsdirtyratio 5
	aint ro.zygote.disable_gl_preload 1
	aint skia.force_gl_texture 1
	aint sys.display_panel_lpm true
	aint sys.init.perf_lsm_hooks 1
	aint sys.use_fifo_ui 1
	aint vendor.debug.sf.latch_unsignaled 1
	aint vendor.gralloc.disable_ubwc 0
	aint video.accelerate.hw 1
	aint view.scroll_friction 0
	aint view.touch_slop 1
	aint visual_bars false
	aint vm.stat_interval 1
	aint windowsmgr.max_events_per_sec 200
	
	aint ro.mtk_perf_fast_start_win 1
	aint ro.mtk_perf_response_time 1
	aint ro.mtk_perf_simple_start_win 1
	
	aint ro.surface_flinger.refresh_rate_switching 120
	aint ro.surface_flinger.set_display_power_timer_ms 1000
	aint ro.surface_flinger.set_touch_timer_ms 200
	aint ro.surface_flinger.use_content_detection_for_refresh_rate false
	
	aint ro.adreno.android Android P/Q
	aint ro.adreno.arch arm64
	aint ro.adreno.edition Vulkan
	aint ro.adreno.sdk 28
	aint ro.adreno.series 500
	aint ro.adreno.soc msm8998
	aint ro.adreno.version 4.5
	aint ro.adreno.vulkan 1.1.128
	
	aint debug.disable.thermal.control 1
	aint debug.disable.usb.overheat.mitigation 1
	aint persist.sys.fan.thermal_auto 1
	aint persist.sys.thermal.disable true
	aint persist.vendor.disable.thermal.control 1
	aint ro.vendor.disable.thermal.control 1
	aint ro.vendor.disable.usb.overheat.mitigation 1
	aint ro.vendor.fps.switch.default false
	aint ro.vendor.fps.switch.thermal true
	aint ro.vendor.thermal.dimming.enable false
	aint ro.vendor.thermal.manager.is_ht120 1
	aint ro.vendor.thermal.product 2
	aint sys.thermal.data.path /data/vendor/thermal/
	aint vendor.disable.thermal.control 1
	aint vendor.disable.usb.overheat.mitigation 1
	aint vendor.thermal.manager.is_ht120 1
	aint persist.traced.enable 0
	aint persist.traced_perf.enable 0
	aint persist.sys.lmk.reportkills false
	aint sys.lmk.reportkills false
	aint ro.lmk.debug false
	aint ro.lmk.log_stats false
	aint vendor.vidc.debug.level 0
	aint vidc.debug.level 0
	
	aint persist.service.zram 1
	aint persist.sys.zram_enabled 1
	aint ro.zram.default 4294967296
	aint vm.swappiness 100
	
	aint ro.gfx.angle.supported true
	
	aint ro.HOME_APP_ADJ 1
	
	aint debug.als.logs 0
	aint debug.atrace.tags.enableflags 0
	aint debug.mdpcomp.logs 0
	aint debug.svi.logs 0
	aint debugtool.anrhistory 0
	aint log.tag.stats_log 0
	aint logcat.live disable
	aint logd.logpersistd.enable false
	aint logd.statistics 0
	aint persist.debug.trace 0
	aint persist.sample.eyetracking.log 0
	aint persist.service.adb.enable 0
	aint persist.service.debuggable 0
	aint persist.sys.loglevel 0
	aint persist.traced.enable 0
	aint persist.vendor.verbose_logging_enabled false
	aint profiler.hung.dumpdobugreport false
	aint ro.logd.size.stats 0
	aint ro.logd.size 0
	aint sys.log.app 0
}&

settings put system min_refresh_rate 120
settings put system peak_refresh_rate 120.00001

# Using crokrammgmtfix @crok based source

function zramswapper()
{
	if [ $(getprop ro.build.version.release) -gt 9 ]; then
		cmd device_config set_sync_disabled_for_tests persistent
		cmd device_config put activity_manager max_cached_processes 256 || settings put global activity_manager_constants max_cached_processes=256
		cmd device_config put activity_manager max_phantom_processes 2147483647
		cmd settings put global settings_enable_monitor_phantom_procs false
		cmd device_config put activity_manager max_empty_time_millis 43200000
		cmd settings put global settings_enable_monitor_phantom_procs false
	fi
	
	sleep 1
	if true; then
		am start -a android.intent.action.MAIN -e message 'personalbuild by nothing' -n com.personal.build/.ShowToast; else
		su -c am start -a android.intent.action.MAIN -e message 'personalbuild by nothing' -n com.personal.build/.ShowToast
	fi
}

zramswapper;

personal()
{
	MODDIR="${0%/*}"
	MODNAME="${MODDIR##*/}"
	PROPFILE="$MAGISKTMP/.magisk/modules/$MODNAME/module.prop"
	TMPFILE="/data/adb/modules/$MODNAME/module.prop"
}

{
	personal;
	
	if ${0%/*}/disable; then
		cp -af "$MODDIR/module.prop" "$TMPFILE"
		sed -Ei 's/^description=(\[.*][[:space:]]*)?/description=Nothing end /g' "$TMPFILE"
		flock "$MODDIR/module.prop"
		mount --bind "$TMPFILE" "$PROPFILE"
		chmod 777 "$MODDIR/personalbuild"
	else
		cp -af "$MODDIR/module.prop" "$TMPFILE"
		sed -Ei 's/^description=(\[.*][[:space:]]*)?/description=Nothing no end /g' "$TMPFILE"
		flock "$MODDIR/module.prop"
		mount --bind "$TMPFILE" "$PROPFILE"
		chmod 777 "$MODDIR/personalbuild"
	fi
}&

sysbat;

exit 0
