#!/system/bin/sh

# Special to Ktweaks @tytydraco based source

# Stealing ain't cool
MAGISKTMP="$(magisk --path)" || MAGISKTMP=/sbin

sync

while [[ "$(getprop sys.boot_completed)" -ne 1 ]] && [[ ! -d "/sdcard" ]]
do
    sleep 1
done

if [[ "$(id -u)" -ne 0 ]]
then
	echo "No root permissions. Exiting."
	exit 1
fi

write() {
	[[ ! -f "$1" ]] && return 1
	
	chmod +w "$1" 2> /dev/null

	if ! echo "$2" > "$1" 2> /dev/null
	then
		echo "Failed: $1 → $2"
		return 1
	fi
}

(while :
do
    sf=$(service list | grep -c "SurfaceFlinger")
    
    if [ $sf -eq 1 ]
    then
        service call SurfaceFlinger 1008 i32 1
        break
    else
        sleep 1
    fi
done
) &

for i in /sys/block/*/queue/read_ahead_kb
do
echo 4096 > "$i"
done

for i in /sys/block/*/queue/nr_requests
do
echo 512 > "$i"
done

echo 0 > /sys/devices/platform/soc/1d84000.ufshc/clkgate_enable
echo 0 > /sys/devices/platform/soc/1d84000.ufshc/clkscale_enable
echo 0 > /sys/devices/platform/soc/1d84000.ufshc/hibern8_on_idle_enable

for i in /sys/block/*/queue/read_ahead_kb
do
echo 4096 > "$i"
done

for i in /sys/block/*/queue/nr_requests
do
echo 128 > "$i"
done

echo 1 > /sys/devices/platform/soc/1d84000.ufshc/clkgate_enable
echo 1 > /sys/devices/platform/soc/1d84000.ufshc/clkscale_enable
echo 1 > /sys/devices/platform/soc/1d84000.ufshc/hibern8_on_idle_enable

for i in /sys/block/*/queue/iostats
do
echo 0 > "$i"
done 

for i in /sys/module/*/parameters/debug_mask
do 
echo 0 > "$i"
done

for i in /sys/module/*/parameters/debug_level 
do 
echo 0 > "$i"
done

if [ "$(getprop init.svc.logd)" = running ]; then
stop logd
fi 

if [ "$(getprop init.svc.statsd)" = running ]; then
stop statsd
fi 

write /sys/kernel/debug/sched_features HRTICK 

write /proc/sys/fs/dir-notify-enable 0
write /proc/sys/vm/stat_interval 10
write /sys/module/printk/parameters/console_suspend Y
write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/kernel/printk 0 0 0 0
write /sys/module/printk/parameters/cpu N
write /sys/kernel/printk_mode/printk_mode 0write /sys/module/printk/parameters/ignore_loglevel Y
write /sys/module/printk/parameters/pid N
write /sys/module/printk/parameters/time N
write /sys/kernel/debug/debug_enabled N
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/vm/oom_dump_tasks 0
write /proc/sys/vm/block_dump 0
write /sys/module/subsystem_restart/parameters/enable_ramdumps 0
write /sys/module/rmnet_data/parameters/rmnet_data_log_level 0
write /sys/kernel/tracing/tracing_on 0
write /sys/kernel/debug/tracing/tracing_on 0
write /proc/sys/kernel/compat-log 0
write /sys/module/logger/parameters/log_enabled 0
write /proc/sys/debug/exception-trace 0
write /sys/module/debug/parameters/enable_event_log 0
write /sys/module/logger/parameters/enabled 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_drv 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_ctxt 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_cmd 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_pwr 0
write /sys/kernel/debug/kgsl/kgsl-3d0/log_level_mem 0
write /sys/module/mali/parameters/mali_debug_level 0
write /sys/module/ext4/parameters/mballoc_debug 0
write /sys/module/rpm_smd/parameters/debug_mask 0
write /sys/module/msm_show_resume_irq/parameters/debug_mask 0
write /sys/module/rmnet_data/parameters/rmnet_data_log_level 0
write /sys/module/ip6_tunnel/parameters/log_ecn_error N
write /sys/module/mmc_core/parameters/use_spi_crc 0

write /dev/stune/top-app/schedtune.boost 10
write /dev/stune/top-app/schedtune.prefer_idle 1
write /dev/stune/foreground/schedtune.prefer_idle 1
write dev/cpuset/background/cpus 0-3
write dev/cpuset/foreground/cpus 0-7

UINT_MAX="4294967295"
SCHED_PERIOD="$((1 * 1000 * 1000))"
SCHED_TASKS="10"

grep -q android /proc/cmdline && ANDROID=true

write /proc/sys/kernel/perf_cpu_time_max_percent 3
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
write /proc/sys/kernel/sched_migration_cost_ns 5000000

[[ "$ANDROID" == true ]] && write /proc/sys/kernel/sched_min_task_util_for_colocation 0

write /proc/sys/kernel/sched_nr_migrate 4
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/vm/dirty_background_ratio 3
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 200
write /proc/sys/net/ipv4/tcp_ecn 1
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/net/ipv4/tcp_syncookies 0

if [[ -f "/sys/kernel/debug/sched_features" ]]
then
	write /sys/kernel/debug/sched_features NEXT_BUDDY
	write /sys/kernel/debug/sched_features NO_TTWU_QUEUE
fi

[[ "$ANDROID" == true ]] && if [[ -d "/dev/stune/" ]]
then
	write /dev/stune/top-app/schedtune.prefer_idle 1
	write /dev/stune/top-app/schedtune.boost 1
fi

for cpu in /sys/devices/system/cpu/cpu*/cpufreq
do
	avail_govs="$(cat "$cpu/scaling_available_governors")"
	
	for governor in performance schedutil interactive
	do
		if [[ "$avail_govs" == *"$governor"* ]]
		then
			write "$cpu/scaling_governor" "$governor"
			break
		fi
	done
done

find /sys/devices/system/cpu/ -name schedutil -type d | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" 0
	write "$governor/down_rate_limit_us" 0
	write "$governor/rate_limit_us" 0
	write "$governor/hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -name interactive -type d | while IFS= read -r governor
do
	write "$governor/timer_rate" 0
	write "$governor/min_sample_time" 0
	write "$governor/go_hispeed_load" 85
	write "$governor/hispeed_freq" "$UINT_MAX"
done

for queue in /sys/block/*/queue
do
	avail_scheds="$(cat "$queue/scheduler")"
	
	for sched in cfq noop kyber bfq mq-deadline none
	do
		if [[ "$avail_scheds" == *"$sched"* ]]
		then
			write "$queue/scheduler" "$sched"
			break
		fi
	done
	write "$queue/add_random" 0
	write "$queue/iostats" 0
	write "$queue/read_ahead_kb" 4096
	write "$queue/nr_requests" 32
done

UINT_MAX="4294967295"
SCHED_PERIOD="$((4 * 1000 * 1000))"
SCHED_TASKS="8"

grep -q android /proc/cmdline && ANDROID=true

write /proc/sys/kernel/perf_cpu_time_max_percent 5
write /proc/sys/kernel/sched_autogroup_enabled 1
write /proc/sys/kernel/sched_child_runs_first 1
write /proc/sys/kernel/sched_tunable_scaling 0
write /proc/sys/kernel/sched_latency_ns "$SCHED_PERIOD"
write /proc/sys/kernel/sched_min_granularity_ns "$((SCHED_PERIOD / SCHED_TASKS))"
write /proc/sys/kernel/sched_wakeup_granularity_ns "$((SCHED_PERIOD / 2))"
write /proc/sys/kernel/sched_migration_cost_ns 5000000

[[ "$ANDROID" == true ]] && write /proc/sys/kernel/sched_min_task_util_for_colocation 0

write /proc/sys/kernel/sched_nr_migrate 32
write /proc/sys/kernel/sched_schedstats 0
write /proc/sys/kernel/printk_devkmsg off
write /proc/sys/vm/dirty_background_ratio 10
write /proc/sys/vm/dirty_ratio 30
write /proc/sys/vm/dirty_expire_centisecs 3000
write /proc/sys/vm/dirty_writeback_centisecs 3000
write /proc/sys/vm/page-cluster 0
write /proc/sys/vm/stat_interval 10
write /proc/sys/vm/swappiness 100
write /proc/sys/vm/vfs_cache_pressure 100
write /proc/sys/net/ipv4/tcp_ecn 1
write /proc/sys/net/ipv4/tcp_fastopen 3
write /proc/sys/net/ipv4/tcp_syncookies 0

if [[ -f "/sys/kernel/debug/sched_features" ]]
then
	write /sys/kernel/debug/sched_features NEXT_BUDDY
	write /sys/kernel/debug/sched_features TTWU_QUEUE
fi

[[ "$ANDROID" == true ]] && if [[ -d "/dev/stune/" ]]
then
	write /dev/stune/top-app/schedtune.prefer_idle 0
	write /dev/stune/top-app/schedtune.boost 1
fi

for cpu in /sys/devices/system/cpu/cpu*/cpufreq
do
	avail_govs="$(cat "$cpu/scaling_available_governors")"

	for governor in performance schedutil interactive
	do
		if [[ "$avail_govs" == *"$governor"* ]]
		then
			write "$cpu/scaling_governor" "$governor"
			break
		fi
	done
done

find /sys/devices/system/cpu/ -name schedutil -type d | while IFS= read -r governor
do
	write "$governor/up_rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/down_rate_limit_us" "$((4 * SCHED_PERIOD / 1000))"
	write "$governor/rate_limit_us" "$((SCHED_PERIOD / 1000))"
	write "$governor/hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

find /sys/devices/system/cpu/ -name interactive -type d | while IFS= read -r governor
do
	write "$governor/timer_rate" "$((SCHED_PERIOD / 1000))"
	write "$governor/min_sample_time" "$((SCHED_PERIOD / 1000))"
	write "$governor/go_hispeed_load" 90
	write "$governor/hispeed_freq" "$UINT_MAX"
done

for queue in /sys/block/*/queue
do
	avail_scheds="$(cat "$queue/scheduler")"
	for sched in cfq noop kyber bfq mq-deadline none
	do
		if [[ "$avail_scheds" == *"$sched"* ]]
		then
			write "$queue/scheduler" "$sched"
			break
		fi
	done
	write "$queue/add_random" 0
	write "$queue/iostats" 0
	write "$queue/read_ahead_kb" 4096
	write "$queue/nr_requests" 64
done

write /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpufreq/policy0/scaling_governor performance
write /sys/devices/system/cpu/cpufreq/policy4/scaling_governor performance
write /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay 0
write /sys/devices/system/cpu/cpufreq/performance/boost 1
write /sys/devices/system/cpu/cpufreq/performance/go_hispeed_load 75
write /sys/devices/system/cpu/cpufreq/performance/max_freq_hysteresis 1
write /sys/devices/system/cpu/cpufreq/performance/align_windows 1
write /sys/kernel/gpu/gpu_governor performance
write /sys/module/adreno_idler/parameters/adreno_idler_active 0
write /sys/module/lazyplug/parameters/nr_possible_cores 8
write /sys/module/msm_performance/parameters/touchboost 1
write /dev/cpuset/foreground/boost/cpus 4-7
write /dev/cpuset/foreground/cpus 0-3,4-7
write /dev/cpuset/top-app/cpus 0-7

write /proc/sys/vm/page-cluster 0
write /sys/block/zram0/max_comp_streams 4

function biglittlecore()
{
	echo "1 768000:90" > /sys/devices/system/cpu/cpu4/cpufreq/performance/target_loads
	echo "1 960000:85 1094400:90 1344000:80" > /sys/devices/system/cpu/cpu0/cpufreq/performance/target_loads
	echo "1 960000:85 1094400:90" > /sys/devices/system/cpu/cpufreq/performance/target_loads
	echo "19000 1094400:39000" > /sys/devices/system/cpu/cpu0/cpufreq/performance/above_hispeed_delay
	echo "19000 1094400:39000" > /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay
	echo "19000 1401600:39000" > /sys/devices/system/cpu/cpufreq/performance/above_hispeed_delay
	echo "85 1401600:80" > /sys/devices/system/cpu/cpufreq/performance/target_loads
	echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
	echo "performance" > /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor
	echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpu0/cpufreq/performance/rate_limit_us
	echo 0 > /sys/devices/system/cpu/cpu0/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu0/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu1/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu1/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu2/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu2/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu3/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu3/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpu4/cpufreq/performance/rate_limit_us
	echo 0 > /sys/devices/system/cpu/cpu4/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu4/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu5/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu5/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu6/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu6/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpu7/sched_prefer_idle
	echo 0 > /sys/devices/system/cpu/cpu7/sched_static_cpu_pwr_cost
	echo 0 > /sys/devices/system/cpu/cpufreq/performance/io_is_busy
	echo 0 > /sys/devices/system/cpu/cpufreq/performance/rate_limit_us
	echo 1 > /proc/sys/kernel/sched_prefer_sync_wakee_to_waker
	echo 1 > /proc/sys/kernel/sched_restrict_cluster_spill
	echo 1 > /proc/sys/kernel/sched_restrict_tasks_spread
	echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/performance/use_sched_load
	echo 1 > /sys/devices/system/cpu/cpu0/online
	echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpu4/cpufreq/performance/use_sched_load
	echo 1 > /sys/devices/system/cpu/cpu4/online
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/use_migration_notif
	echo 1 > /sys/devices/system/cpu/cpufreq/performance/use_sched_load
	echo 1094400 > /sys/devices/system/cpu/cpu0/cpufreq/performance/hispeed_freq
	echo 1094400 > /sys/devices/system/cpu/cpufreq/performance/hispeed_freq
	echo 1401600 > /sys/devices/system/cpu/cpufreq/performance/hispeed_freq
	echo 19 > /proc/sys/kernel/sched_upmigrate_min_nice
	echo 20 > /proc/sys/kernel/sched_small_task
	echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/timer_rate
	echo 20000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/timer_rate
	echo 20000 > /sys/devices/system/cpu/cpufreq/performance/timer_rate
	echo 200000 > /proc/sys/kernel/sched_freq_dec_notify
	echo 200000 > /proc/sys/kernel/sched_freq_inc_notify
	echo 3 > /proc/sys/kernel/sched_ravg_hist_size
	echo 3 > /proc/sys/kernel/sched_spill_nr_run
	echo 3 > /proc/sys/kernel/sched_window_stats_policy
	echo 3 > /sys/devices/system/cpu/cpu0/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu1/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu2/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu3/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu4/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu5/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu6/sched_mostly_idle_nr_run
	echo 3 > /sys/devices/system/cpu/cpu7/sched_mostly_idle_nr_run
	echo 30 > /sys/devices/system/cpu/cpu0/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu1/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu2/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu3/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu4/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu5/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu6/sched_mostly_idle_load
	echo 30 > /sys/devices/system/cpu/cpu7/sched_mostly_idle_load
	echo 39000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/above_hispeed_delay
	echo 39000 > /sys/devices/system/cpu/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu0/cpufreq/performance/sampling_down_factor
	echo 40000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/sampling_down_factor
	echo 40000 > /sys/devices/system/cpu/cpufreq/performance/min_sample_time
	echo 40000 > /sys/devices/system/cpu/cpufreq/performance/sampling_down_factor
	echo 50000 > /proc/sys/kernel/sched_freq_dec_notify
	echo 50000 > /proc/sys/kernel/sched_freq_inc_notify
	echo 768000 > /sys/devices/system/cpu/cpu4/cpufreq/performance/hispeed_freq
	echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/performance/go_hispeed_load
	echo 85 > /sys/devices/system/cpu/cpu0/cpufreq/performance/hispeed_load
	echo 85 > /sys/devices/system/cpu/cpu4/cpufreq/performance/hispeed_load
	echo 85 > /sys/devices/system/cpu/cpufreq/performance/go_hispeed_load
	echo 85 > /sys/devices/system/cpu/cpufreq/performance/hispeed_load
	echo 90 > /sys/devices/system/cpu/cpu4/cpufreq/performance/go_hispeed_load
	
	if true; then
		su 2000 -c "cmd notification post -S bigtext -t 'options by nothing' 'Tag' '
function biglittlecore()
{
	executive, done
}'"; else
		su -lp 2000 -c "cmd notification post -S bigtext -t 'options by nothing' 'Tag' '
function biglittlecore()
{
	executive, done
}'"
	fi
}

biglittlecore

# Personalidentify
{
	resetprop -v -n debug.atrace.tags.enableflags 0
	resetprop -v -n debug.composition.type dyn
	resetprop -v -n debug.egl.buffcount 4
	resetprop -v -n debug.egl.force_msaa 1
	resetprop -v -n debug.egl.force_msaa true
	resetprop -v -n debug.egl.hw 1
	resetprop -v -n debug.enabletr true
	resetprop -v -n debug.gr.swapinterval 0
	resetprop -v -n debug.gralloc.gfx_ubwc_disable 0
	resetprop -v -n debug.hwui.capture_skp_enabled false
	resetprop -v -n debug.hwui.disable_draw_defer true
	resetprop -v -n debug.hwui.disable_draw_reorder true
	resetprop -v -n debug.hwui.filter_test_overhead false
	resetprop -v -n debug.hwui.level 0
	resetprop -v -n debug.hwui.overdraw false
	resetprop -v -n debug.hwui.renderer skiagl
	resetprop -v -n debug.hwui.show_dirty_regions false
	resetprop -v -n debug.hwui.show_layers_updates false
	resetprop -v -n debug.hwui.show_non_rect_clip hide
	resetprop -v -n debug.hwui.skip_empty_damage true
	resetprop -v -n debug.hwui.skp_filename /sdcard/0
	resetprop -v -n debug.hwui.use_buffer_age false
	resetprop -v -n debug.hwui.use_gpu_pixel_buffers false
	resetprop -v -n debug.hwui.use_partial_updates false
	resetprop -v -n debug.mdpcomp.4k2kSplit 1
	resetprop -v -n debug.mdpcomp.idletime 9000
	resetprop -v -n debug.mdpcomp.logs 0
	resetprop -v -n debug.overlayui.enable 1
	resetprop -v -n debug.performance.tuning 1
	resetprop -v -n debug.sf.disable_backpressure 1
	resetprop -v -n debug.sf.enable_advanced_sf_phase_offset 1
	resetprop -v -n debug.sf.enable_gl_backpressure 1
	resetprop -v -n debug.sf.enable_hwc_vds 1
	resetprop -v -n debug.sf.hw 1
	resetprop -v -n debug.sf.latch_unsignaled 1
	resetprop -v -n fku.perf.profile 1
	resetprop -v -n hw3d.force 1
	resetprop -v -n hwui.disable_vsync true
	resetprop -v -n hwui.private_hal_readback 1
	resetprop -v -n hwui.render_dirty_regions false
	resetprop -v -n log.tag.stats_log 0
	resetprop -v -n logd.logpersistd.enable false
	resetprop -v -n logd.statistics 0
	resetprop -v -n persist.hwc.mdpcomp.enable true
	resetprop -v -n persist.sys.composition.type dyn
	resetprop -v -n persist.sys.strictmode.disable 1
	resetprop -v -n persist.sys.strictmode.visual 0
	resetprop -v -n persist.sys.ui.hw 1
	resetprop -v -n persist.traced.enable 0
	resetprop -v -n persist.vendor.color.matrix 2
	resetprop -v -n persist.vendor.qti.inputopts.enable true
	resetprop -v -n persist.vendor.qti.inputopts.movetouchslop 0.6
	resetprop -v -n persist.vendor.verbose_logging_enabled false
	resetprop -v -n ro.config.enable.hw_accel true
	resetprop -v -n ro.fb.mode 1
	resetprop -v -n ro.hwui.drop_shadow_cache_size 6
	resetprop -v -n ro.hwui.gradient_cache_size 1
	resetprop -v -n ro.hwui.layer_cache_size 48
	resetprop -v -n ro.hwui.path_cache_size 32
	resetprop -v -n ro.hwui.r_buffer_cache_size 8
	resetprop -v -n ro.hwui.text_large_cache_height 1024
	resetprop -v -n ro.hwui.text_large_cache_width 2048
	resetprop -v -n ro.hwui.text_small_cache_height 1024
	resetprop -v -n ro.hwui.text_small_cache_width 1024
	resetprop -v -n ro.hwui.texture_cache_flushrate 0.4
	resetprop -v -n ro.hwui.texture_cache_size 72
	resetprop -v -n ro.logd.size 0
	resetprop -v -n ro.logd.size.stats 0
	resetprop -v -n ro.product.gpu.driver 1
	resetprop -v -n ro.sf.compbypass.enable 0
	resetprop -v -n ro.vendor.qti.config.zram true
	resetprop -v -n ro.vendor.qti.core.ctl_max_cpu 4
	resetprop -v -n ro.vendor.qti.core.ctl_min_cpu 2
	resetprop -v -n ro.vendor.qti.sys.fw.bservice_enable true
	resetprop -v -n ro.vendor.tran_perf_plus 1
	resetprop -v -n skia.force_gl_texture 1
	resetprop -v -n sys.init.perf_lsm_hooks 1
	resetprop -v -n vendor.debug.sf.latch_unsignaled 1
	resetprop -v -n vendor.gralloc.disable_ubwc 0
	resetprop -v -n video.accelerate.hw 1
	resetprop -v -n visual_bars false
	resetprop -v -n debug.drm.mode.force 1600x720@120
	resetprop -v -n debug.cpurend.vsync false
	
	resetprop -v -n ro.surface_flinger.use_content_detection_for_refresh_rate false
	resetprop -v -n ro.surface_flinger.refresh_rate_switching 120
	resetprop -v -n ro.surface_flinger.set_display_power_timer_ms 1000
	resetprop -v -n ro.surface_flinger.set_touch_timer_ms 200
	resetprop -v -n ro.surface_flinger.use_content_detection_for_refresh_rate false
	
	resetprop -v -n vendor.thermal.manager.is_ht120 1
	resetprop -v -n vendor.disable.usb.overheat.mitigation 1
	resetprop -v -n vendor.disable.thermal.control 1
	resetprop -v -n sys.thermal.data.path /data/vendor/thermal/
	resetprop -v -n ro.vendor.thermal.product 2
	resetprop -v -n ro.vendor.thermal.manager.is_ht120 1
	resetprop -v -n ro.vendor.thermal.dimming.enable false
	resetprop -v -n ro.vendor.fps.switch.thermal true
	resetprop -v -n ro.vendor.fps.switch.default true
	resetprop -v -n ro.vendor.disable.usb.overheat.mitigation 1
	resetprop -v -n ro.vendor.disable.thermal.control 1
	resetprop -v -n persist.vendor.disable.thermal.control 1
	resetprop -v -n persist.sys.thermal.disable true
	resetprop -v -n persist.sys.fan.thermal_auto 0
	resetprop -v -n debug.disable.usb.overheat.mitigation 1
	resetprop -v -n debug.disable.thermal.control 1
}&

settings put system min_refresh_rate 120
settings put system peak_refresh_rate 120.00001

personal() {
	MODDIR="${0%/*}"
	MODNAME="${MODDIR##*/}"
	MAGISKTMP="$(magisk --path)" || MAGISKTMP=/sbin
	PROPFILE="$MAGISKTMP/.magisk/modules/$MODNAME/module.prop"
	TMPFILE="/data/adb/modules/$MODNAME/module.prop"
}

{
	personal
	cp -af "$MODDIR/module.prop" "$TMPFILE"
	sed -Ei 's/^description=(\[.*][[:space:]]*)?/description=Nothing no end /g' "$TMPFILE"
	flock "$MODDIR/module.prop"
	mount --bind "$TMPFILE" "$PROPFILE"
	chmod 755 "$MODDIR/personalbuild"
}&

exit 0
