#!/bin/sh

# Built-in scene perf QCOM™, mtSoC Mediatek
chmod 755 /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu1/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu2/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu3/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu4/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu5/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu6/cpufreq/cpuinfo_max_freq
chmod 755 /sys/devices/system/cpu/cpu7/cpufreq/cpuinfo_max_freq

chmod 755 /sys/devices/system/cpu/cpu0/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu1/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu2/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu3/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu4/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu5/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu6/cpu_capacity
chmod 755 /sys/devices/system/cpu/cpu7/cpu_capacity

chmod 755 /sys/devices/system/cpu/cpu0/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu1/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu2/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu3/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu4/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu5/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu6/topology/physical_package_id
chmod 755 /sys/devices/system/cpu/cpu7/topology/physical_package_id

chmod 755 /sys/class/power_supply/*/*
chmod 755 /sys/class/power_supply/battery/*
chmod 755 /sys/class/power_supply/mtk-gauge/*
chmod 755 /sys/class/power_supply/mtk-master-charger/*
chmod 755 /sys/class/power_supply/mtk-slave-charger/*
chmod 755 /sys/class/power_supply/mtk_charger_type/*
chmod 755 /sys/class/power_supply/usb/*
chmod 755 /sys/module/dwc3_msm/*/*
chmod 755 /sys/module/phy_msm_usb/*/*
chmod 755 /sys/module/qpnp_smbcharger/*/*

echo 0 > /sys/devices/system/cpu/cpu0/core_ctl/enable

# Built-in scene fc QCOM™, mtSoC Mediatek
echo 0 > /sys/class/power_supply/battery/input_current_limited
echo 0 > /sys/class/qcom-battery/restricted_charging

echo 1 > /sys/class/power_supply/battery/allow_hvdcp3
echo 1 > /sys/class/power_supply/battery/input_current_settled
echo 1 > /sys/class/power_supply/battery/subsystem/usb/pd_allowed
echo 1 > /sys/class/power_supply/battery/system_temp_level
echo 1 > /sys/class/power_supply/usb/pd_allowed
echo 1 > /sys/kernel/fast_charge/failsafe
echo 1 > /sys/kernel/fast_charge/force_fast_charge

echo 1 > /sys/class/power_supply/mtk-master-charger/voltage_max
echo 1 > /sys/class/power_supply/mtk-slave-charger/voltage_max

# Make sure that before booting it runs, cause issue because it detects after post-fs-data.sh
build()
{
	MODDIR="${0%/*}"
	MODNAME="${MODDIR##*/}"
	PROPFILE="$MAGISKTMP/.magisk/modules/$MODNAME/module.prop"
	TMPFILE="/data/adb/modules/$MODNAME/module.prop"
}

{
	build;
	
	cp -af "$MODDIR/module.prop" "$TMPFILE"
	sed -Ei 's/^description=(\[.*][[:space:]]*)?/description=/g' "$TMPFILE"
	flock "$MODDIR/module.prop"
	mount --bind "$TMPFILE" "$PROPFILE"
	chmod 777 "$MODDIR/scene"
}&

exit 0
