#!/system/bin/sh

# Another battery calibration based on dumpsys

# Initialize battery value before loop
previous_battery_level=$(cat /sys/class/power_supply/battery/capacity)

while true; do
  sysbat=$(cat /sys/class/power_supply/battery/capacity)

  if [ $sysbat -gt $previous_battery_level ]; then
    dumpsys batterystats --reset-all
    previous_battery_level=$sysbat
    
    if true; then
      su 2000 -c "cmd notification post -S bigtext -t 'optimization charging by nothing' 'Tag' '
previous: $previous_battery_level%
$sysbat% - Battery stats and history reset.'"; else
      su -lp 2000 -c "cmd notification post -S bigtext -t 'optimization charging by nothing' 'Tag' '
previous: $previous_battery_level%
$sysbat% - Battery stats and history reset.'"
    fi
  fi

  sleep 1
done

exit 0
