#!/system/bin/sh

# Another battery calibration based on dumpsys

# Initialize battery value and status before loop
previous_battery_level=$(cat /sys/class/power_supply/battery/capacity)
notification_sent=false

while true; do
  sysbat=$(cat /sys/class/power_supply/battery/capacity)

  if [ $sysbat -eq 100 ]; then
	if [ $sysbat -gt $previous_battery_level ]; then
		if [ "$notification_sent" = false ]; then
    		dumpsys batterystats --reset-all
    		previous_battery_level=$sysbat
    
    		if true; then
su 2000 -c "cmd notification post -S bigtext -t 'optimization charging by nothing' 'Tag' '
previous: $previous_battery_level%
$sysbat% - Battery stats and history reset.'";else
su -lp 2000 -c "cmd notification post -S bigtext -t 'optimization charging by nothing' 'Tag' '
previous: $previous_battery_level%
$sysbat% - Battery stats and history reset.'"
    		fi
    
    	# Set notification_sent to true
    	notification_sent=true
  	elif [ $sysbat -lt 100 ]; then
    	# Reset notification_sent when battery level is less than 100%
    	notification_sent=false
  	fi

  sleep 1
done

exit 0
